Minor changes. Some output changed.

diff --git a/glsysbackup b/glsysbackup
--- a/glsysbackup
+++ b/glsysbackup
@@ -11,7 +11,7 @@
 #  Project website:	https://github.com/ccztux/glsysbackup
 #
 #  Last Modification:	Christian Zettel (ccztux)
-#			2017-03-23
+#			2017-03-24
 #
 #  Description:		Generic Linux System Backup is an advanced backup tool written in bash.
 #
@@ -39,9 +39,9 @@
 # Bash options:
 #--------------
 
-set -o noclobber || { printf "Essential bash option: 'noclobber' can not be set, terminating...\n" ; exit 245 ; }
-set -o nounset || { printf "Essential bash option: 'nounset' can not be set, terminating...\n" ; exit 246 ; }
-set -o pipefail || { printf "Essential bash option: 'pipefail' can not be set, terminating...\n" ; exit 247 ; }
+set -o noclobber || { printf "Setting essential bash option: 'noclobber' was not successful, terminating...\n" ; exit 245 ; }
+set -o nounset || { printf "Setting essential bash option: 'nounset' was not successful, terminating...\n" ; exit 246 ; }
+set -o pipefail || { printf "Setting essential bash option: 'pipefail' was not successful, terminating...\n" ; exit 247 ; }
 
 
 
@@ -49,13 +49,13 @@ set -o pipefail || { printf "Essential bash option: 'pipefail' can not be set, t
 # Traps:
 #-------
 
-trap 'siggHandler SIGTERM' SIGTERM || { printf "Essential trap for signal: 'SIGTERM' can not be set, terminating...\n" ; exit 248 ; }
-trap 'sigHandler SIGINT' SIGINT || { printf "Essential trap for signal: 'SIGINT' can not be set, terminating...\n" ; exit 249 ; }
-trap 'sigHandler SIGHUP' SIGHUP || { printf "Essential trap for signal: 'SIGHUP' can not be set, terminating...\n" ; exit 250 ; }
-trap 'sigHandler SIGABRT' SIGABRT || { printf "Essential trap for signal: 'SIGABRT' can not be set, terminating...\n" ; exit 251 ; }
-trap 'sigHandler SIGQUIT' SIGQUIT || { printf "Essential trap for signal: 'SIGQUIT' can not be set, terminating...\n" ; exit 252 ; }
-trap 'sigHandler ERR "${LINENO}" "${BASH_COMMAND}"' ERR || { printf "Essential trap for signal: 'ERR' can not be set, terminating...\n" ; exit 253 ; }
-trap 'sigHandler EXIT' EXIT || { printf "Essential trap for signal: 'EXIT' can not be set, terminating...\n" ; exit 254 ; }
+trap 'siggHandler SIGTERM' SIGTERM || { printf "Setting essential trap for signal: 'SIGTERM' was not successful, terminating...\n" ; exit 248 ; }
+trap 'sigHandler SIGINT' SIGINT || { printf "Setting essential trap for signal: 'SIGINT' was not successful, terminating...\n" ; exit 249 ; }
+trap 'sigHandler SIGHUP' SIGHUP || { printf "Setting essential trap for signal: 'SIGHUP' was not successful, terminating...\n" ; exit 250 ; }
+trap 'sigHandler SIGABRT' SIGABRT || { printf "Setting essential trap for signal: 'SIGABRT' was not successful, terminating...\n" ; exit 251 ; }
+trap 'sigHandler SIGQUIT' SIGQUIT || { printf "Setting essential trap for signal: 'SIGQUIT' was not successful, terminating...\n" ; exit 252 ; }
+trap 'sigHandler ERR "${LINENO}" "${BASH_COMMAND}"' ERR || { printf "Setting essential trap for signal: 'ERR' was not successful, terminating...\n" ; exit 253 ; }
+trap 'sigHandler EXIT' EXIT || { printf "Setting essential trap for signal: 'EXIT' was not successful, terminating...\n" ; exit 254 ; }
 
 
 
@@ -70,7 +70,7 @@ script_version="1.0.1-alpha3"
 script_author="Christian Zettel (ccztux)"
 script_copyright="Copyright © 2017 ${script_author}, all rights reserved"
 script_project_website="https://github.com/ccztux/glsysbackup"
-script_last_modification_date="2017-03-23"
+script_last_modification_date="2017-03-24"
 script_license="GNU GPLv3"
 script_description="${script_name} (Generic Linux System Backup) is an advanced backup tool written in bash."
 script_exit_code="255"
@@ -140,7 +140,7 @@ printUsage()
 	printf "OPTIONS:\n"
 	printf "   -h\t\tShows this help.\n"
 	printf "   -o\t\tOverride lock in case %s was terminated abnormally.\n" "${script_name}"
-	printf "   -v\t\tShows detailed script information.\n"
+	printf "   -v\t\tShows detailed version information.\n"
 
 	if [ "${log_to_stdout}" == "1" ] ;then
 		printf "\n"
@@ -480,6 +480,7 @@ sigHandler()
 				if [ "${script_another_instance_is_running}" != "1" ] ;then
 					checkLock
 					rc="$?"
+
 					if [ "${rc}" == "0" ] ;then
 						removeLock
 					fi
@@ -552,13 +553,13 @@ setLock()
 				logHandler "Creating script lock directory was successful."
 			else
 				logHandler "Creating script lock directory was not successful."
-				script_exit_code="40"
+				script_exit_code="10"
 				exit
 			fi
 			;;
 		*)
 			logHandler "Script lock directory exists but permissions are not ok, exiting."
-			script_exit_code="41"
+			script_exit_code="11"
 			exit
 			;;
 	esac
@@ -572,7 +573,7 @@ setLock()
 		logHandler "Setting lock was successful."
 	else
 		logHandler "Setting lock was not successful. Maybe another instance has set the lock between checking lock and setting lock."
-		script_exit_code="42"
+		script_exit_code="12"
 		exit
 	fi
 }
@@ -587,7 +588,7 @@ removeLock()
 		logHandler "Removing lock was successful."
 	else
 		logHandler "Removing lock was not successful."
-		script_exit_code="50"
+		script_exit_code="20"
 		exit
 	fi
 }
@@ -629,7 +630,7 @@ delUnencryptedBackupFile()
 					logHandler "Deleting unencrypted backup file was successful."
 				else
 					logHandler "Deleting unencrypted backup file was not successful."
-					script_exit_code="120"
+					script_exit_code="30"
 				fi
 				;;
 			10)
@@ -637,7 +638,7 @@ delUnencryptedBackupFile()
 				;;
 			*)
 				logHandler "Unencrypted backup file is not writeable, we can not delete it."
-				script_exit_code="121"
+				script_exit_code="311"
 				;;
 		esac
 	fi
@@ -665,7 +666,7 @@ delInstalledPackagesFile()
 					logHandler "Deleting installed packages file was successful."
 				else
 					logHandler "Deleting installed packages file was not successful."
-					script_exit_code="130"
+					script_exit_code="40"
 				fi
 				;;
 			10)
@@ -673,7 +674,7 @@ delInstalledPackagesFile()
 				;;
 			*)
 				logHandler "Installed packages file exists, but it is not writeable, we can not delete it."
-				script_exit_code="131"
+				script_exit_code="41"
 				;;
 		esac
 	fi
@@ -820,7 +821,7 @@ checkRootPrivileges()
 			logHandler "HOORAY, we have root privileges. :)"
 		else
 			logHandler "You must run this script as root, terminating."
-			script_exit_code="10"
+			script_exit_code="50"
 			exit
 		fi
 	else
@@ -831,7 +832,7 @@ checkRootPrivileges()
 getUser()
 {
 	local rc=
-	script_exec_user=
+	local script_exec_user=
 
 	logHandler "Get user which starts the script..."
 
@@ -850,7 +851,7 @@ checkBashVersion()
 
 	if [ -z "${BASH_VERSINFO[0]}" ] ;then
 		logHandler "Could not determine bash version, exiting."
-		script_exit_code="20"
+		script_exit_code="60"
 		exit
 	else
 		case "${BASH_VERSINFO[0]}" in
@@ -862,7 +863,7 @@ checkBashVersion()
 						;;
 					*)
 						logHandler "Bash version: '${BASH_VERSINFO[0]}' doesnt meet requirements, terminating."
-						script_exit_code="21"
+						script_exit_code="61"
 						exit
 						;;
 		esac
@@ -882,6 +883,7 @@ checkAlreadyRunningInstance()
 
 	checkLock
 	rc="$?"
+
 	if ([ "${rc}" != "0" ] && [ -z "${running_script_pids:-}" ]) ;then
 		logHandler "No other instance of: '${script_name}' is currently running (Lockfile: '${script_lock_file}' doesnt exist and no processes are running)."
 		setLock
@@ -894,7 +896,7 @@ checkAlreadyRunningInstance()
 			logHandler "HINT: You can override the old left over lock by calling ${script_name} with option '-o'."
 
 			script_another_instance_is_running="1"
-			script_exit_code="30"
+			script_exit_code="70"
 			exit
 		fi
 	elif ([ "${rc}" == "0" ] && [ ! -z "${running_script_pids:-}" ]) ;then
@@ -903,7 +905,7 @@ checkAlreadyRunningInstance()
 		logHandler "Another instance of: '${script_name}' is currently running (Lockfile: '${script_lock_file}' exists and the following processes: '${running_script_pids}' are running)."
 
 		script_another_instance_is_running="1"
-		script_exit_code="31"
+		script_exit_code="71"
 		exit
 	elif ([ "${rc}" != "0" ] && [ ! -z "${running_script_pids:-}" ]) ;then
 		running_script_pids="${running_script_pids:0:$((${#running_script_pids} - 2))}"
@@ -911,7 +913,7 @@ checkAlreadyRunningInstance()
 		logHandler "Another instance of: '${script_name}' is currently running (Lockfile: '${script_lock_file}' doesnt exist and the following processes: '${running_script_pids}' are running)."
 
 		script_another_instance_is_running="1"
-		script_exit_code="32"
+		script_exit_code="72"
 		exit
 	fi
 }
@@ -928,7 +930,7 @@ reNice()
 			logHandler "Re-nice priority: '${re_nice_priority}' is out of range."
 			logHandler "HINT: Have a look at: 'man renice'."
 
-			script_exit_code="10"
+			script_exit_code="80"
 			exit
 		else
 			logHandler "Re-nice priority: '${re_nice_priority}' is in range."
@@ -940,7 +942,7 @@ reNice()
 				logHandler "Re-niceing was successful."
 			else
 				logHandler "Re-niceing was not successful."
-				script_exit_code="11"
+				script_exit_code="81"
 				exit
 			fi
 		fi
@@ -964,7 +966,7 @@ reIONice()
 			logHandler "Re-ioniceing scheduling class: '${re_ionice_scheduling_class}' is out of range."
 			logHandler "HINT: Have a look at: 'man ionice'."
 
-			script_exit_code="20"
+			script_exit_code="90"
 			exit
 		else
 			logHandler "Re-ioniceing scheduling class: '${re_ionice_scheduling_class}' is in range."
@@ -980,7 +982,7 @@ reIONice()
 				logHandler "Re-ioniceing priority: '${re_ionice_priority}' is out of range."
 				logHandler "HINT: Have a look at: 'man ionice'."
 
-				script_exit_code="21"
+				script_exit_code="91"
 				exit
 			else
 				logHandler "Re-ioniceing priority: '${re_ionice_scheduling_class}' is in range."
@@ -1003,7 +1005,7 @@ reIONice()
 			logHandler "Re-ioniceing was successful."
 		else
 			logHandler "Re-ioniceing was not successful."
-			script_exit_code="22"
+			script_exit_code="92"
 			exit
 		fi
 	else
@@ -1080,13 +1082,13 @@ rotateHandler()
 					logHandler "Creating backup directory was successful."
 				else
 					logHandler "Creating backup directory was not successful."
-					script_exit_code="70"
+					script_exit_code="110"
 					exit
 				fi
 				;;
 			*)
 				logHandler "Backup directory exists but permissions are not ok, exiting."
-				script_exit_code="71"
+				script_exit_code="111"
 				exit
 				;;
 		esac
@@ -1133,7 +1135,7 @@ rotateHandler()
 					;;
 				*)
 					logHandler "File exists but is not readable."
-					script_exit_code="72"
+					script_exit_code="112"
 					exit
 					;;
 			esac
@@ -1163,14 +1165,14 @@ createInstalledPackagesFile()
 
 			logHandler "More than one supported syspackage managers found: '${available_syspackage_managers_helper}', dont know what to do, exiting."
 
-			script_exit_code="60"
+			script_exit_code="120"
 			exit
 		elif [ "${#available_syspackage_managers[*]}" -eq "1" ] ;then
 			syspackage_manager="${available_syspackage_managers[*]}"
 			logHandler "The supported system package manager we found is: '${syspackage_manager}'."
 		elif [ "${#available_syspackage_managers[*]}" -eq "0" ] ;then
 			logHandler "No supported system package manager found, exiting."
-			script_exit_code="61"
+			script_exit_code="121"
 			exit
 		fi
 
@@ -1185,7 +1187,7 @@ createInstalledPackagesFile()
 							;;
 						*)
 							logHandler "Ooops!!! Someting went wrong in function: '${FUNCNAME[0]}'. :( Exiting."
-							script_exit_code="62"
+							script_exit_code="122"
 							exit
 							;;
 		esac
@@ -1196,7 +1198,7 @@ createInstalledPackagesFile()
 			logHandler "Creating installed packages file was successful."
 		else
 			logHandler "Creating installed packages file was not successful."
-			script_exit_code="63"
+			script_exit_code="123"
 			exit
 		fi
 	else
@@ -1251,7 +1253,7 @@ makeBackup()
 		script_exit_code="0"
 	else
 		logHandler "Backup job was not successful."
-		script_exit_code="81"
+		script_exit_code="130"
 		exit
 	fi
 }
@@ -1270,7 +1272,7 @@ encryptBackup()
 			script_exit_code="0"
 		else
 			logHandler "Encrypting job was not successful."
-			script_exit_code="90"
+			script_exit_code="140"
 			exit
 		fi
 	else
@@ -1295,12 +1297,12 @@ executePostBackupScript()
 				;;
 			10)
 				logHandler "Post backup script doesnt exist, nothing to do."
-				script_exit_code="110"
+				script_exit_code="150"
 				exit
 				;;
 			*)
 				logHandler "Post backup script exists, but it is not executeable, nothing to do."
-				script_exit_code="111"
+				script_exit_code="151"
 				exit
 				;;
 		esac
