Switch: backup_rotating_required added.

diff --git a/glsysbackup b/glsysbackup
--- a/glsysbackup
+++ b/glsysbackup
@@ -74,6 +74,8 @@ backup_full_path="${backup_destination_path}${backup_filename}"
 items_to_backup="/home/ /root/ /var/lib/mpd/ /usr/local/bin/ /boot/config.txt"
 items_to_exclude=("/root/old" "/tmp/var")
 
+backup_rotating_required="1"
+
 installed_packages_required="1"
 installed_packages_filename="/root/installed_packages_filename.txt"
 
@@ -400,48 +402,54 @@ buildExcludeOpts()
 
 rotateHandler()
 {
-	local rc=
-	local files_to_keep="$1"
-	logHandler "Rotating backup files..."
-	if [ -z "$files_to_keep" ] ;then
-		local files_to_keep="5"
-	fi
-	if [ "$backup_encryption_required" == "1" ] ;then
-		file="$backup_encryption_filename"
-	else
-		file="$backup_full_path"
-	fi
-	files_to_keep=$(($files_to_keep - 1))
-	while [ "$files_to_keep" -gt "0" ]
-	   do
-		local file_helper=$(($files_to_keep - 1))
-		if [ "$files_to_keep" != "1" ] ;then
-			checkLocalFileExists "${file}.${file_helper}"
-			rc="$?"
-			if [ "$rc" == "0" ] ;then
-				${mv_bin}${file}.${file_helper} ${file}.${files_to_keep} 2>&1 | logHandler
-				rc="${PIPESTATUS[0]}"
-				if [ "$rc" == "0" ] ;then
-					logHandler "Rotating file: '${file}.${file_helper}' ==> '${file}.${files_to_keep}' was successful."
-				else
-					logHandler "Rotating file: '${file}.${file_helper}' ==> '${file}.${files_to_keep}' was not successful."
-				fi
-			fi
+	logHandler "Check if backup rotating is required..."
+	if [ "$backup_rotating_required" == "1" ] ;then
+		logHandler "Backup rotating is required..."
+		local rc=
+		local files_to_keep="$1"
+		logHandler "Rotating backup files..."
+		if [ -z "$files_to_keep" ] ;then
+			local files_to_keep="5"
+		fi
+		if [ "$backup_encryption_required" == "1" ] ;then
+			file="$backup_encryption_filename"
 		else
-			checkLocalFileExists "${file}"
-			rc="$?"
-			if [ "$rc" == "0" ] ;then
-				${mv_bin}${file} ${file}.${files_to_keep} 2>&1 | logHandler
-				rc="${PIPESTATUS[0]}"
-				if [ "$rc" == "0" ] ;then
-					logHandler "Rotating file: '${file}' ==> '${file}.${files_to_keep}' was successful."
-				else
-					logHandler "Rotating file: '${file}' ==> '${file}.${files_to_keep}' was not successful."
-				fi
-			fi
+			file="$backup_full_path"
 		fi
 		files_to_keep=$(($files_to_keep - 1))
-	   done
+		while [ "$files_to_keep" -gt "0" ]
+		   do
+			local file_helper=$(($files_to_keep - 1))
+			if [ "$files_to_keep" != "1" ] ;then
+				checkLocalFileExists "${file}.${file_helper}"
+				rc="$?"
+				if [ "$rc" == "0" ] ;then
+					${mv_bin}${file}.${file_helper} ${file}.${files_to_keep} 2>&1 | logHandler
+					rc="${PIPESTATUS[0]}"
+					if [ "$rc" == "0" ] ;then
+						logHandler "Rotating file: '${file}.${file_helper}' ==> '${file}.${files_to_keep}' was successful."
+					else
+						logHandler "Rotating file: '${file}.${file_helper}' ==> '${file}.${files_to_keep}' was not successful."
+					fi
+				fi
+			else
+				checkLocalFileExists "${file}"
+				rc="$?"
+				if [ "$rc" == "0" ] ;then
+					${mv_bin}${file} ${file}.${files_to_keep} 2>&1 | logHandler
+					rc="${PIPESTATUS[0]}"
+					if [ "$rc" == "0" ] ;then
+						logHandler "Rotating file: '${file}' ==> '${file}.${files_to_keep}' was successful."
+					else
+						logHandler "Rotating file: '${file}' ==> '${file}.${files_to_keep}' was not successful."
+					fi
+				fi
+			fi
+			files_to_keep=$(($files_to_keep - 1))
+		   done
+	else
+		logHandler "Backup rotating is not required..."
+	fi
 }
 
 logHandler()
