Function: checkBin added, reworked function: getSysPackageManager

diff --git a/glsysbackup b/glsysbackup
--- a/glsysbackup
+++ b/glsysbackup
@@ -230,6 +230,29 @@ checkLocalFileExists()
 	fi
 }
 
+checkBin()
+{
+	local binary="$1"
+	local rc=
+	if [ -z "$binary" ] ;then
+		logHandler "Function: '${FUNCNAME}' called without required argument, nothing to do, exiting..."
+		script_exit_code="112"
+		exit
+	else
+		logHandler "Check if binary '${binary}' exists."
+		export ${binary}_bin="`which \"${binary}\" 2>&1`"
+		rc="$?"
+		if [ "$rc" == "0" ] ;then
+			logHandler "Binary: '${binary}' found."
+			return 0
+		else
+			logHandler "Binary: '${binary}' not found, exiting..."
+			script_exit_code="111"
+			exit
+		fi
+	fi
+}
+
 checkTrailingSlash()
 {
 	local path="$1"
@@ -248,14 +271,26 @@ removeLastChar()
 
 getSysPackageManager()
 {
-	local dpkg="`which dpkg 2> /dev/null`"
-	local rpm="`which rpm 2> /dev/null`"
-	if [ ! -z "$dpkg" ] ;then
-		syspackage_manager="$dpkg"
-		${syspackage_manager} --get-selections > $installed_packages
-	elif [ ! -z "$rpm" ] ;then
-		syspackage_manager="$rpm"
-		${syspackage_manager} -qa > $installed_packages
+	local supported_syspackage_managers=("rpm" "dpkg")
+	local available_syspackage_managers=()
+	for syspackman in ${supported_syspackage_managers[*]}
+	   do
+		available_syspackage_managers+=("`checkBin \"$syspackman\"`")
+	   done
+	if [ "${#available_syspackage_managers[*]}" -gt "1" ] ;then
+		logHandler "More than one supported syspackage managers found: '${available_syspackage_managers[*]}', dont know what to do..."
+		return 1
+	else
+		case "${available_syspackage_managers}" in
+							rpm)
+								${rpm_bin} -qa > $installed_packages
+								;;
+							dpkg)
+								${dpkg_bin} --get-selections > $installed_packages
+								;;
+							*)
+								;;
+		esac
 	fi
 }
 
